export interface RosterPlayer {
  id: string;
  name: string;
  number: number;
  position: string;
}

export const teamRosters: Record<string, RosterPlayer[]> = {
  "acacia-guardians": [
    { id: "g1", name: "Marcus Johnson", number: 12, position: "QB" },
    { id: "g2", name: "David Chen", number: 4, position: "WR" },
    { id: "g3", name: "Elijah Washington", number: 21, position: "RB" },
    { id: "g4", name: "Tyler Brooks", number: 88, position: "TE" },
    { id: "g5", name: "Samir Patel", number: 10, position: "WR" },
    { id: "g6", name: "Lucas Ramirez", number: 55, position: "LB" },
    { id: "g7", name: "Jackson Hayes", number: 7, position: "DB" },
    { id: "g8", name: "Omar Thompson", number: 24, position: "DB" },
    { id: "g9", name: "Wyatt Cooper", number: 52, position: "DL" },
    { id: "g10", name: "Caleb Wright", number: 90, position: "DL" },
    { id: "g11", name: "Benjamin Foster", number: 33, position: "LB" },
  ],
  "mission-hills-mountaineers": [
    { id: "m1", name: "Julian Martinez", number: 8, position: "QB" },
    { id: "m2", name: "Kevin O'Connor", number: 1, position: "WR" },
    { id: "m3", name: "Andre Smith", number: 28, position: "RB" },
    { id: "m4", name: "Nathaniel Price", number: 85, position: "TE" },
    { id: "m5", name: "Derek Torres", number: 14, position: "WR" },
    { id: "m6", name: "Stephen Clark", number: 58, position: "LB" },
    { id: "m7", name: "Anthony Lewis", number: 2, position: "DB" },
    { id: "m8", name: "Brian Evans", number: 26, position: "DB" },
    { id: "m9", name: "Carlos Gomez", number: 99, position: "DL" },
    { id: "m10", name: "Ian Mitchell", number: 92, position: "DL" },
    { id: "m11", name: "Thomas Reed", number: 44, position: "LB" },
  ],
  "anthem-hills-antelopes": [
    { id: "a1", name: "Zachary Taylor", number: 15, position: "QB" },
    { id: "a2", name: "Brandon Lee", number: 11, position: "WR" },
    { id: "a3", name: "Cameron White", number: 22, position: "RB" },
    { id: "a4", name: "Jordan Davis", number: 89, position: "TE" },
    { id: "a5", name: "Evan Rodriguez", number: 18, position: "WR" },
    { id: "a6", name: "Matthew Green", number: 50, position: "LB" },
    { id: "a7", name: "Ryan King", number: 5, position: "DB" },
    { id: "a8", name: "Jason Scott", number: 29, position: "DB" },
    { id: "a9", name: "William Baker", number: 77, position: "DL" },
    { id: "a10", name: "Aaron Nelson", number: 95, position: "DL" },
    { id: "a11", name: "Justin Carter", number: 41, position: "LB" },
  ],
  "heritage-hawkeyes": [
    { id: "h1", name: "Daniel Perez", number: 9, position: "QB" },
    { id: "h2", name: "Alexander Wood", number: 3, position: "WR" },
    { id: "h3", name: "Christopher Hall", number: 30, position: "RB" },
    { id: "h4", name: "Andrew Young", number: 82, position: "TE" },
    { id: "h5", name: "Joseph Allen", number: 17, position: "WR" },
    { id: "h6", name: "Nicholas King", number: 54, position: "LB" },
    { id: "h7", name: "Joshua Wright", number: 20, position: "DB" },
    { id: "h8", name: "Christian Lopez", number: 31, position: "DB" },
    { id: "h9", name: "Jonathan Hill", number: 91, position: "DL" },
    { id: "h10", name: "Dylan Scott", number: 96, position: "DL" },
    { id: "h11", name: "Gabriel Adams", number: 42, position: "LB" },
  ],
  "hidden-falls-falcons": [
    { id: "f1", name: "Ethan Harris", number: 16, position: "QB" },
    { id: "f2", name: "Noah Campbell", number: 6, position: "WR" },
    { id: "f3", name: "Mason Mitchell", number: 25, position: "RB" },
    { id: "f4", name: "Logan Roberts", number: 87, position: "TE" },
    { id: "f5", name: "Oliver Phillips", number: 19, position: "WR" },
    { id: "f6", name: "Elijah Evans", number: 56, position: "LB" },
    { id: "f7", name: "Carter Turner", number: 23, position: "DB" },
    { id: "f8", name: "Luke Parker", number: 32, position: "DB" },
    { id: "f9", name: "Owen Collins", number: 93, position: "DL" },
    { id: "f10", name: "Wyatt Edwards", number: 97, position: "DL" },
    { id: "f11", name: "Jack Stewart", number: 45, position: "LB" },
  ],
  "cornerstone-cougars": [
    { id: "c1", name: "Leo Morris", number: 14, position: "QB" },
    { id: "c2", name: "Isaac Rogers", number: 13, position: "WR" },
    { id: "c3", name: "Levi Murphy", number: 27, position: "RB" },
    { id: "c4", name: "Micah Rivera", number: 84, position: "TE" },
    { id: "c5", name: "Julian Cook", number: 80, position: "WR" },
    { id: "c6", name: "Josiah Morgan", number: 51, position: "LB" },
    { id: "c7", name: "Isaiah Bell", number: 9, position: "DB" },
    { id: "c8", name: "Lincoln Cooper", number: 34, position: "DB" },
    { id: "c9", name: "Mateo Reed", number: 94, position: "DL" },
    { id: "c10", name: "Ryan Bailey", number: 98, position: "DL" },
    { id: "c11", name: "Asher Kelly", number: 46, position: "LB" },
  ],
  "arroyo-grande-aces": [
    { id: "ag1", name: "Tyson Howard", number: 4, position: "QB" },
    { id: "ag2", name: "Adrian Ward", number: 10, position: "WR" },
    { id: "ag3", name: "Colton Cox", number: 35, position: "RB" },
    { id: "ag4", name: "Hudson Diaz", number: 81, position: "TE" },
    { id: "ag5", name: "Nolan Richardson", number: 83, position: "WR" },
    { id: "ag6", name: "Roman Wood", number: 53, position: "LB" },
    { id: "ag7", name: "Ezra Watson", number: 12, position: "DB" },
    { id: "ag8", name: "Miles Brooks", number: 36, position: "DB" },
    { id: "ag9", name: "Greyson Bennett", number: 75, position: "DL" },
    { id: "ag10", name: "Weston Gray", number: 78, position: "DL" },
    { id: "ag11", name: "Silas James", number: 47, position: "LB" },
  ],
  "pecos-pioneers": [
    { id: "p1", name: "Declan Hughes", number: 2, position: "QB" },
    { id: "p2", name: "Emmett Price", number: 15, position: "WR" },
    { id: "p3", name: "Rowan Myers", number: 20, position: "RB" },
    { id: "p4", name: "Harrison Long", number: 86, position: "TE" },
    { id: "p5", name: "Jasper Foster", number: 88, position: "WR" },
    { id: "p6", name: "Maxwell Sanders", number: 59, position: "LB" },
    { id: "p7", name: "Gavin Ross", number: 21, position: "DB" },
    { id: "p8", name: "Cole Powell", number: 37, position: "DB" },
    { id: "p9", name: "Tristan Sullivan", number: 72, position: "DL" },
    { id: "p10", name: "Jonah Russell", number: 79, position: "DL" },
    { id: "p11", name: "Micah Ortiz", number: 48, position: "LB" },
  ],
  "discovery-desert-devils": [
    { id: "d1", name: "Dominic Jenkins", number: 7, position: "QB" },
    { id: "d2", name: "Xavier Perry", number: 18, position: "WR" },
    { id: "d3", name: "Austin Powell", number: 24, position: "RB" },
    { id: "d4", name: "Victor Long", number: 89, position: "TE" },
    { id: "d5", name: "Colin Patterson", number: 82, position: "WR" },
    { id: "d6", name: "Preston Hughes", number: 57, position: "LB" },
    { id: "d7", name: "Marcus Washington", number: 11, position: "DB" },
    { id: "d8", name: "Blake Simmons", number: 38, position: "DB" },
    { id: "d9", name: "Zane Foster", number: 74, position: "DL" },
    { id: "d10", name: "Riley Bryant", number: 76, position: "DL" },
    { id: "d11", name: "Brady Alexander", number: 49, position: "LB" },
  ],
};
